// Usik Music Library - Curated Streaming Catalog (Bollywood, Hollywood, Lo-Fi & Spatial Audio)

export const TRACKS_DATA = [
  // ==========================================
  // BOLLYWOOD MEGA ANTHEMS
  // ==========================================
  {
    id: "track-bolly-1",
    title: "Tum Hi Ho",
    artist: "Arijit Singh",
    album: "Aashiqui 2",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 262,
    type: "youtube",
    videoId: "Umqb9KENgmk",
    audioUrl: "https://www.youtube.com/watch?v=Umqb9KENgmk",
    embedUrl: "https://www.youtube.com/embed/Umqb9KENgmk",
    coverUrl: "https://i.ytimg.com/vi/Umqb9KENgmk/hqdefault.jpg",
    color: "#ec4899",
    secondaryColor: "#a855f7",
    featured: true,
    lyrics: [
      "Hum tere bin ab reh nahi sakte",
      "Tere bina kya wajood mera",
      "Tujhse juda agar ho jaayenge",
      "Toh khud se hi ho jaayenge judaa",
      "Kyunki tum hi ho, ab tum hi ho",
      "Zindagi ab tum hi ho",
      "Chain bhi, mera dard bhi",
      "Meri aashiqui ab tum hi ho"
    ]
  },
  {
    id: "track-bolly-2",
    title: "Kesariya",
    artist: "Arijit Singh, Pritam",
    album: "Brahmāstra",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 268,
    type: "youtube",
    videoId: "BddP6PYo2gs",
    audioUrl: "https://www.youtube.com/watch?v=BddP6PYo2gs",
    embedUrl: "https://www.youtube.com/embed/BddP6PYo2gs",
    coverUrl: "https://i.ytimg.com/vi/BddP6PYo2gs/hqdefault.jpg",
    color: "#f59e0b",
    secondaryColor: "#ef4444",
    featured: true,
    lyrics: [
      "Mujhko itna bataye koi",
      "Kaise tujhse dil na lagaye koi",
      "Rabba ne tujhko banane mein",
      "Kar di hai husn ki khaali tijoriyan",
      "Kesariya tera ishq hai piya",
      "Rang jaaun jo main haath lagaun",
      "Din beete saara teri fikr mein",
      "Rain saari teri khair manaun"
    ]
  },
  {
    id: "track-bolly-3",
    title: "Kun Faya Kun",
    artist: "A.R. Rahman, Javed Ali, Mohit Chauhan",
    album: "Rockstar",
    genre: "Bollywood",
    mood: "Relax",
    duration: 472,
    type: "youtube",
    videoId: "T94PHkuydcw",
    audioUrl: "https://www.youtube.com/watch?v=T94PHkuydcw",
    embedUrl: "https://www.youtube.com/embed/T94PHkuydcw",
    coverUrl: "https://i.ytimg.com/vi/T94PHkuydcw/hqdefault.jpg",
    color: "#06b6d4",
    secondaryColor: "#6366f1",
    featured: true,
    lyrics: [
      "Ya Nizamuddin Auliya",
      "Kun faya kun, kun faya kun",
      "Faya kun, faya kun, faya kun",
      "Jab kahin pe kuch nahi bhi nahi tha",
      "Wahi tha wahi tha wahi tha",
      "Sajda bajaun, sar jhukaun",
      "O re piya re, rang roop tera re",
      "Kun faya kun"
    ]
  },
  {
    id: "track-bolly-4",
    title: "Channa Mereya",
    artist: "Arijit Singh, Pritam",
    album: "Ae Dil Hai Mushkil",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 289,
    type: "youtube",
    videoId: "bzSTpdcs-EI",
    audioUrl: "https://www.youtube.com/watch?v=bzSTpdcs-EI",
    embedUrl: "https://www.youtube.com/embed/bzSTpdcs-EI",
    coverUrl: "https://i.ytimg.com/vi/bzSTpdcs-EI/hqdefault.jpg",
    color: "#f43f5e",
    secondaryColor: "#e11d48",
    featured: true,
    lyrics: [
      "Achha chalta hoon, duaon mein yaad rakhna",
      "Mere zikr ka zubaan pe swaad rakhna",
      "Dil ke sandookon mein mere achhe kaam rakhna",
      "Chithi taaron mein bhi mera tu salaam rakhna",
      "Andhera tera maine le liya",
      "Mera ujla sitaara tere naam kiya",
      "Channa mereya mereya, channa mereya mereya",
      "Beliya o piya"
    ]
  },
  {
    id: "track-bolly-5",
    title: "Kabira",
    artist: "Tochi Raina, Rekha Bhardwaj, Pritam",
    album: "Yeh Jawaani Hai Deewani",
    genre: "Bollywood",
    mood: "Acoustic",
    duration: 224,
    type: "youtube",
    videoId: "jHNNMj5bNQw",
    audioUrl: "https://www.youtube.com/watch?v=jHNNMj5bNQw",
    embedUrl: "https://www.youtube.com/embed/jHNNMj5bNQw",
    coverUrl: "https://i.ytimg.com/vi/jHNNMj5bNQw/hqdefault.jpg",
    color: "#d97706",
    secondaryColor: "#b45309",
    featured: false,
    lyrics: [
      "Kaisi teri khudgarzi",
      "Na dhoop chune na chhaanv",
      "Kaisi teri khudgarzi",
      "Kisi thor tike na paanv",
      "Ban liya apna paighambar",
      "Tar liya tu saat samandar",
      "Re Kabira maan jaa",
      "Re Faqeera yun na jaa"
    ]
  },
  {
    id: "track-bolly-6",
    title: "Agar Tum Saath Ho",
    artist: "Alka Yagnik, Arijit Singh, A.R. Rahman",
    album: "Tamasha",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 341,
    type: "youtube",
    videoId: "sK7riqg2mr4",
    audioUrl: "https://www.youtube.com/watch?v=sK7riqg2mr4",
    embedUrl: "https://www.youtube.com/embed/sK7riqg2mr4",
    coverUrl: "https://i.ytimg.com/vi/sK7riqg2mr4/hqdefault.jpg",
    color: "#475569",
    secondaryColor: "#7c3aed",
    featured: true,
    lyrics: [
      "Pal bhar thehar jaao, dil yeh sambhal jaaye",
      "Kaise tumhe rokein, aansu nikal jaaye",
      "Dil ko tumhaari zaroorat hai",
      "Agar tum saath ho",
      "Har gham aasaan lagta hai",
      "Agar tum saath ho",
      "Behti hawa sa tha woh",
      "Kahaan gaya use dhoondho"
    ]
  },
  {
    id: "track-bolly-7",
    title: "Kal Ho Naa Ho",
    artist: "Sonu Nigam, Shankar-Ehsaan-Loy",
    album: "Kal Ho Naa Ho",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 321,
    type: "youtube",
    videoId: "g0eO74UmRBs",
    audioUrl: "https://www.youtube.com/watch?v=g0eO74UmRBs",
    embedUrl: "https://www.youtube.com/embed/g0eO74UmRBs",
    coverUrl: "https://i.ytimg.com/vi/g0eO74UmRBs/hqdefault.jpg",
    color: "#3b82f6",
    secondaryColor: "#6366f1",
    featured: false,
    lyrics: [
      "Har ghadi badal rahi hai roop zindagi",
      "Chhaanv hai kabhi, kabhi hai dhoop zindagi",
      "Har pal yahan jee bhar jiyo",
      "Jo hai samaan, kal ho naa ho",
      "Chaahe jo tumhe poore dil se",
      "Milta hai woh mushkil se",
      "Aisa jo koi kahin hai",
      "Bas wahi sabse haseen hai"
    ]
  },
  {
    id: "track-bolly-8",
    title: "Ghungroo",
    artist: "Arijit Singh, Shilpa Rao, Vishal-Shekhar",
    album: "War",
    genre: "Bollywood",
    mood: "Energy",
    duration: 302,
    type: "youtube",
    videoId: "qFkNATtc3mc",
    audioUrl: "https://www.youtube.com/watch?v=qFkNATtc3mc",
    embedUrl: "https://www.youtube.com/embed/qFkNATtc3mc",
    coverUrl: "https://i.ytimg.com/vi/qFkNATtc3mc/hqdefault.jpg",
    color: "#06b6d4",
    secondaryColor: "#ec4899",
    featured: false,
    lyrics: [
      "Kyun lamhe kharaab karein",
      "Aa ghalti behisaab karein",
      "Do pal ki jo neend udi",
      "Aao poore saare khwaab karein",
      "Ghungroo toot gaye",
      "Chhalke jaam yahan",
      "Bheegi raat mein hum",
      "Ghungroo toot gaye"
    ]
  },
  {
    id: "track-bolly-9",
    title: "Apna Bana Le",
    artist: "Arijit Singh, Sachin-Jigar",
    album: "Bhediya",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 261,
    type: "youtube",
    videoId: "ElZfdU54Cp8",
    audioUrl: "https://www.youtube.com/watch?v=ElZfdU54Cp8",
    embedUrl: "https://www.youtube.com/embed/ElZfdU54Cp8",
    coverUrl: "https://i.ytimg.com/vi/ElZfdU54Cp8/hqdefault.jpg",
    color: "#8b5cf6",
    secondaryColor: "#ec4899",
    featured: true,
    lyrics: [
      "Tu mera koi na hoke bhi kuch laage",
      "Kiya re jo bhi tune kaale jaadu jaage",
      "Apna bana le piya, apna bana le piya",
      "Dil ke nagar mein shehar tu basa le piya",
      "Chhoo le tu aise mujhe jaise koi dua",
      "Apna bana le piya"
    ]
  },
  {
    id: "track-bolly-10",
    title: "Raataan Lambiyan",
    artist: "Jubin Nautiyal, Asees Kaur, Tanishk Bagchi",
    album: "Shershaah",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 230,
    type: "youtube",
    videoId: "gvyUuxdRdR4",
    audioUrl: "https://www.youtube.com/watch?v=gvyUuxdRdR4",
    embedUrl: "https://www.youtube.com/embed/gvyUuxdRdR4",
    coverUrl: "https://i.ytimg.com/vi/gvyUuxdRdR4/hqdefault.jpg",
    color: "#10b981",
    secondaryColor: "#3b82f6",
    featured: false,
    lyrics: [
      "Teri meri gallan ho gayi mashhur",
      "Kar na kabhi tu mujhe nazron se door",
      "Kithe chaliye tu kithe chaliye",
      "Kaatun kaise raataan, o saawre?",
      "Jiya nahi jaata, sun bawre",
      "Ke raataan lambiyan lambiyan re",
      "Katt-te tere sangeyan sangeyan re"
    ]
  },
  {
    id: "track-bolly-11",
    title: "Ilahi",
    artist: "Arijit Singh, Pritam",
    album: "Yeh Jawaani Hai Deewani",
    genre: "Bollywood",
    mood: "Energy",
    duration: 228,
    type: "youtube",
    videoId: "fdubeMFwuGs",
    audioUrl: "https://www.youtube.com/watch?v=fdubeMFwuGs",
    embedUrl: "https://www.youtube.com/embed/fdubeMFwuGs",
    coverUrl: "https://i.ytimg.com/vi/fdubeMFwuGs/hqdefault.jpg",
    color: "#f59e0b",
    secondaryColor: "#10b981",
    featured: false,
    lyrics: [
      "Shaamein malang si",
      "Raatein patang si",
      "Dagar-dagar bhatakti hai",
      "Ghoomti awara si",
      "Mera aasmaan dhoondhe",
      "Mera jahaan dhoondhe",
      "Ilahi mera jee aaye aaye",
      "Kal pe sawaal hai, jeena filhaal hai"
    ]
  },
  {
    id: "track-bolly-12",
    title: "Gerua",
    artist: "Arijit Singh, Antara Mitra, Pritam",
    album: "Dilwale",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 345,
    type: "youtube",
    videoId: "AEIVhBS6baE",
    audioUrl: "https://www.youtube.com/watch?v=AEIVhBS6baE",
    embedUrl: "https://www.youtube.com/embed/AEIVhBS6baE",
    coverUrl: "https://i.ytimg.com/vi/AEIVhBS6baE/hqdefault.jpg",
    color: "#ea580c",
    secondaryColor: "#f43f5e",
    featured: false,
    lyrics: [
      "Dhoop se nikalke, chhaanv se phisalke",
      "Hum mile jahan par, lamha tham gaya",
      "Aasmaan pighal ke, sheeshe mein dhal ke",
      "Rang sharbaton ka ban gaya",
      "Rang de tu mohe gerua",
      "Ranjhe ki dil se hai dua",
      "Rang de tu mohe gerua"
    ]
  },
  {
    id: "track-bolly-13",
    title: "Hawayein",
    artist: "Arijit Singh, Pritam",
    album: "Jab Harry Met Sejal",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 290,
    type: "youtube",
    videoId: "cYOB941gyXI",
    audioUrl: "https://www.youtube.com/watch?v=cYOB941gyXI",
    embedUrl: "https://www.youtube.com/embed/cYOB941gyXI",
    coverUrl: "https://i.ytimg.com/vi/cYOB941gyXI/hqdefault.jpg",
    color: "#38bdf8",
    secondaryColor: "#818cf8",
    featured: false,
    lyrics: [
      "Tujhko... main rakh loon wahan",
      "Jahan pe kahin hai mera yaqeen",
      "Main jo jee raha hoon, wajah tum ho",
      "Wajah tum ho",
      "Le jaayein jaane kahan hawayein, hawayein",
      "Le jaayein tujhe kahan hawayein, hawayein",
      "Begaani hai yeh baaghi hawayein"
    ]
  },
  {
    id: "track-bolly-14",
    title: "Dil Diyan Gallan",
    artist: "Atif Aslam, Vishal-Shekhar",
    album: "Tiger Zinda Hai",
    genre: "Bollywood",
    mood: "Romantic",
    duration: 260,
    type: "youtube",
    videoId: "SAcpESN_Fk4",
    audioUrl: "https://www.youtube.com/watch?v=SAcpESN_Fk4",
    embedUrl: "https://www.youtube.com/embed/SAcpESN_Fk4",
    coverUrl: "https://i.ytimg.com/vi/SAcpESN_Fk4/hqdefault.jpg",
    color: "#be185d",
    secondaryColor: "#9333ea",
    featured: false,
    lyrics: [
      "Kacchi doriyon, doriyon, doriyon se",
      "Mainu tu baandh le",
      "Pakkiyan yaariyan, yaariyan, yaariyan mein",
      "Honde na faasle",
      "Dil diyan gallan karange naal naal beh ke",
      "Akh naale akh nu mila ke",
      "Rabb wargi tu lagdi ae"
    ]
  },
  {
    id: "track-bolly-15",
    title: "Jhoome Jo Pathaan",
    artist: "Arijit Singh, Sukriti Kakar, Vishal-Shekhar",
    album: "Pathaan",
    genre: "Bollywood",
    mood: "Energy",
    duration: 202,
    type: "youtube",
    videoId: "YxWlaYCA8MU",
    audioUrl: "https://www.youtube.com/watch?v=YxWlaYCA8MU",
    embedUrl: "https://www.youtube.com/embed/YxWlaYCA8MU",
    coverUrl: "https://i.ytimg.com/vi/YxWlaYCA8MU/hqdefault.jpg",
    color: "#f97316",
    secondaryColor: "#ef4444",
    featured: true,
    lyrics: [
      "Tumne mohabbat karni hai, humne mohabbat ki hai",
      "Iss dil ke alawa kisi se bhi, na humne ijazat li hai",
      "Hunar hai yeh bhi ishq ka, kisi kisi ko aata hai",
      "Jhoome jo Pathaan meri jaan",
      "Mehfil hi lut jaaye",
      "Dede jo zubaan meri jaan",
      "Uspe mar mit jaaye"
    ]
  },
  {
    id: "track-bolly-16",
    title: "Naacho Naacho (RRR)",
    artist: "Vishal Mishra, Rahul Sipligunj, M.M. Keeravani",
    album: "RRR",
    genre: "Bollywood",
    mood: "Energy",
    duration: 215,
    type: "youtube",
    videoId: "sAzlWScHTc4",
    audioUrl: "https://www.youtube.com/watch?v=sAzlWScHTc4",
    embedUrl: "https://www.youtube.com/embed/sAzlWScHTc4",
    coverUrl: "https://i.ytimg.com/vi/sAzlWScHTc4/hqdefault.jpg",
    color: "#dc2626",
    secondaryColor: "#f59e0b",
    featured: false,
    lyrics: [
      "Gheech-pinja gheech-pinja",
      "Dhool jhaad ke",
      "Naacho naacho naacho yaaron",
      "Dholak taash bajaao saare",
      "Naacho naacho naacho yaaron",
      "Dharti hilaake dhoom machaao"
    ]
  },
  {
    id: "track-bolly-17",
    title: "Oh Oh Jane Jaana",
    artist: "Kamaal Khan, Jatin-Lalit",
    album: "Pyaar Kiya Toh Darna Kya",
    genre: "Bollywood",
    mood: "Energy",
    duration: 344,
    type: "youtube",
    videoId: "x_elT6zkqN0",
    audioUrl: "https://www.youtube.com/watch?v=x_elT6zkqN0",
    embedUrl: "https://www.youtube.com/embed/x_elT6zkqN0",
    coverUrl: "https://i.ytimg.com/vi/x_elT6zkqN0/hqdefault.jpg",
    color: "#0284c7",
    secondaryColor: "#0ea5e9",
    featured: false,
    lyrics: [
      "I love you all!",
      "O o jaane jaana, dhoondhe tujhe deewana",
      "Sapno mein roz aaye, aa zindagi mein aana sanam",
      "Mera khwaab hai tu, meri aarzoo",
      "Jaan-e-jaan tu kahan hai?"
    ]
  },
  {
    id: "track-bolly-18",
    title: "Pasoori",
    artist: "Ali Sethi, Shae Gill",
    album: "Coke Studio Season 14",
    genre: "Bollywood",
    mood: "Energy",
    duration: 224,
    type: "youtube",
    videoId: "5Eqb_-j3FDA",
    audioUrl: "https://www.youtube.com/watch?v=5Eqb_-j3FDA",
    embedUrl: "https://www.youtube.com/embed/5Eqb_-j3FDA",
    coverUrl: "https://i.ytimg.com/vi/5Eqb_-j3FDA/hqdefault.jpg",
    color: "#e11d48",
    secondaryColor: "#f59e0b",
    featured: true,
    lyrics: [
      "Agg laavan aayi majboori nu",
      "Aan jaan di pasoori nu",
      "Zahar bane haan teri, pee jaavan main poori nu",
      "Raawaan ch baawan ch ohnu lukawaan",
      "Koi mainu na roke",
      "Mere dhol judaiyan di tenu khabar kivein hove"
    ]
  },

  // ==========================================
  // HOLLYWOOD & GLOBAL POP / ROCK / CINEMA
  // ==========================================
  {
    id: "track-holly-1",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    genre: "Hollywood",
    mood: "Energy",
    duration: 200,
    type: "youtube",
    videoId: "4NRXx6U8ABQ",
    audioUrl: "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    embedUrl: "https://www.youtube.com/embed/4NRXx6U8ABQ",
    coverUrl: "https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg",
    color: "#ef4444",
    secondaryColor: "#f59e0b",
    featured: true,
    lyrics: [
      "Yeah",
      "I've been tryin' to call",
      "I've been on my own for long enough",
      "Maybe you can show me how to love, maybe",
      "I'm goin' through withdrawals",
      "You don't even have to do too much",
      "I said, ooh, I'm blinded by the lights",
      "No, I can't sleep until I feel your touch"
    ]
  },
  {
    id: "track-holly-2",
    title: "Starboy",
    artist: "The Weeknd ft. Daft Punk",
    album: "Starboy",
    genre: "Hollywood",
    mood: "Energy",
    duration: 230,
    type: "youtube",
    videoId: "34Na4j8AVgA",
    audioUrl: "https://www.youtube.com/watch?v=34Na4j8AVgA",
    embedUrl: "https://www.youtube.com/embed/34Na4j8AVgA",
    coverUrl: "https://i.ytimg.com/vi/34Na4j8AVgA/hqdefault.jpg",
    color: "#3b82f6",
    secondaryColor: "#ec4899",
    featured: true,
    lyrics: [
      "I'm tryna put you in the worst mood, ah",
      "P1 cleaner than your church shoes, ah",
      "Milli point two just to hurt you, ah",
      "All red Lamb' just to tease you, ah",
      "Look what you've done",
      "I'm a motherfuckin' starboy"
    ]
  },
  {
    id: "track-holly-3",
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "Divide (÷)",
    genre: "Hollywood",
    mood: "Energy",
    duration: 234,
    type: "youtube",
    videoId: "JGwWNGJdvx8",
    audioUrl: "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    embedUrl: "https://www.youtube.com/embed/JGwWNGJdvx8",
    coverUrl: "https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg",
    color: "#06b6d4",
    secondaryColor: "#3b82f6",
    featured: true,
    lyrics: [
      "The club isn't the best place to find a lover",
      "So the bar is where I go",
      "Me and my friends at the table doing shots",
      "Drinking fast and then we talk slow",
      "I'm in love with the shape of you",
      "We push and pull like a magnet do",
      "Although my heart is falling too",
      "I'm in love with your body"
    ]
  },
  {
    id: "track-holly-4",
    title: "Perfect",
    artist: "Ed Sheeran",
    album: "Divide (÷)",
    genre: "Hollywood",
    mood: "Romantic",
    duration: 263,
    type: "youtube",
    videoId: "2Vv-BfVoq4g",
    audioUrl: "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    embedUrl: "https://www.youtube.com/embed/2Vv-BfVoq4g",
    coverUrl: "https://i.ytimg.com/vi/2Vv-BfVoq4g/hqdefault.jpg",
    color: "#f59e0b",
    secondaryColor: "#ec4899",
    featured: false,
    lyrics: [
      "I found a love, for me",
      "Darling, just dive right in and follow my lead",
      "Well, I found a girl, beautiful and sweet",
      "Oh, I never knew you were the someone waiting for me",
      "'Cause we were just kids when we fell in love",
      "Not knowing what it was",
      "I will not give you up this time",
      "Baby, I'm dancing in the dark, with you between my arms"
    ]
  },
  {
    id: "track-holly-5",
    title: "Levitating",
    artist: "Dua Lipa ft. DaBaby",
    album: "Future Nostalgia",
    genre: "Hollywood",
    mood: "Energy",
    duration: 203,
    type: "youtube",
    videoId: "TUVcZfQe-Kw",
    audioUrl: "https://www.youtube.com/watch?v=TUVcZfQe-Kw",
    embedUrl: "https://www.youtube.com/embed/TUVcZfQe-Kw",
    coverUrl: "https://i.ytimg.com/vi/TUVcZfQe-Kw/hqdefault.jpg",
    color: "#8b5cf6",
    secondaryColor: "#ec4899",
    featured: true,
    lyrics: [
      "If you wanna run away with me, I know a galaxy",
      "And I can take you for a ride",
      "I had a premonition that we fell into a rhythm",
      "Where the music don't stop for life",
      "Glitter in the sky, glitter in my eyes",
      "Shining just the way I like",
      "You want me, I want you, baby",
      "My sugarboo, I'm levitating"
    ]
  },
  {
    id: "track-holly-6",
    title: "Bad Guy",
    artist: "Billie Eilish",
    album: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    genre: "Hollywood",
    mood: "Focus",
    duration: 194,
    type: "youtube",
    videoId: "DyDfgMOUjCI",
    audioUrl: "https://www.youtube.com/watch?v=DyDfgMOUjCI",
    embedUrl: "https://www.youtube.com/embed/DyDfgMOUjCI",
    coverUrl: "https://i.ytimg.com/vi/DyDfgMOUjCI/hqdefault.jpg",
    color: "#eab308",
    secondaryColor: "#10b981",
    featured: false,
    lyrics: [
      "White shirt now red, my bloody nose",
      "Sleepin', you're on your tippy toes",
      "Creepin' around like no one knows",
      "Think you're so criminal",
      "So you're a tough guy",
      "Like it really rough guy",
      "Just can't get enough guy",
      "I'm that bad type, make your mama sad type",
      "I'm the bad guy, duh"
    ]
  },
  {
    id: "track-holly-7",
    title: "Lovely",
    artist: "Billie Eilish & Khalid",
    album: "13 Reasons Why: Season 2",
    genre: "Hollywood",
    mood: "Relax",
    duration: 201,
    type: "youtube",
    videoId: "V1Pl8CzNzCw",
    audioUrl: "https://www.youtube.com/watch?v=V1Pl8CzNzCw",
    embedUrl: "https://www.youtube.com/embed/V1Pl8CzNzCw",
    coverUrl: "https://i.ytimg.com/vi/V1Pl8CzNzCw/hqdefault.jpg",
    color: "#64748b",
    secondaryColor: "#38bdf8",
    featured: false,
    lyrics: [
      "Thought I found a way",
      "Thought I found a way out (found)",
      "But you never go away (never go away)",
      "So I guess I gotta stay now",
      "Oh, I hope some day I'll make it out of here",
      "Even if it takes all night or a hundred years",
      "Need a place to hide, but I can't find one near",
      "Isn't it lovely, all alone?"
    ]
  },
  {
    id: "track-holly-8",
    title: "Someone Like You",
    artist: "Adele",
    album: "21",
    genre: "Hollywood",
    mood: "Romantic",
    duration: 285,
    type: "youtube",
    videoId: "hLQl3WQQoQ0",
    audioUrl: "https://www.youtube.com/watch?v=hLQl3WQQoQ0",
    embedUrl: "https://www.youtube.com/embed/hLQl3WQQoQ0",
    coverUrl: "https://i.ytimg.com/vi/hLQl3WQQoQ0/hqdefault.jpg",
    color: "#475569",
    secondaryColor: "#94a3b8",
    featured: false,
    lyrics: [
      "I heard that you're settled down",
      "That you found a girl and you're married now",
      "I heard that your dreams came true",
      "Guess she gave you things I didn't give to you",
      "Never mind, I'll find someone like you",
      "I wish nothing but the best for you too",
      "Don't forget me, I beg, I remember you said",
      "Sometimes it lasts in love, but sometimes it hurts instead"
    ]
  },
  {
    id: "track-holly-9",
    title: "Viva La Vida",
    artist: "Coldplay",
    album: "Viva la Vida or Death and All His Friends",
    genre: "Hollywood",
    mood: "Energy",
    duration: 242,
    type: "youtube",
    videoId: "dvgZkm1xWPE",
    audioUrl: "https://www.youtube.com/watch?v=dvgZkm1xWPE",
    embedUrl: "https://www.youtube.com/embed/dvgZkm1xWPE",
    coverUrl: "https://i.ytimg.com/vi/dvgZkm1xWPE/hqdefault.jpg",
    color: "#f59e0b",
    secondaryColor: "#3b82f6",
    featured: true,
    lyrics: [
      "I used to rule the world",
      "Seas would rise when I gave the word",
      "Now in the morning I sleep alone",
      "Sweep the streets I used to own",
      "I hear Jerusalem bells a-ringin'",
      "Roman Cavalry choirs are singin'",
      "Be my mirror, my sword and shield",
      "My missionaries in a foreign field"
    ]
  },
  {
    id: "track-holly-10",
    title: "Believer",
    artist: "Imagine Dragons",
    album: "Evolve",
    genre: "Hollywood",
    mood: "Energy",
    duration: 204,
    type: "youtube",
    videoId: "7wtfhZwyrcc",
    audioUrl: "https://www.youtube.com/watch?v=7wtfhZwyrcc",
    embedUrl: "https://www.youtube.com/embed/7wtfhZwyrcc",
    coverUrl: "https://i.ytimg.com/vi/7wtfhZwyrcc/hqdefault.jpg",
    color: "#ef4444",
    secondaryColor: "#6366f1",
    featured: true,
    lyrics: [
      "First things first, I'ma say all the words that are on my head",
      "I'm fired up and tired of the way that things have been, oh-ooh",
      "Second thing second, don't you tell me what you think that I can be",
      "I was broken from a young age",
      "Pain! You made me a, you made me a believer, believer",
      "Pain! You break me down and build me up, believer, believer"
    ]
  },
  {
    id: "track-holly-11",
    title: "Counting Stars",
    artist: "OneRepublic",
    album: "Native",
    genre: "Hollywood",
    mood: "Energy",
    duration: 257,
    type: "youtube",
    videoId: "hT_nvWreIhg",
    audioUrl: "https://www.youtube.com/watch?v=hT_nvWreIhg",
    embedUrl: "https://www.youtube.com/embed/hT_nvWreIhg",
    coverUrl: "https://i.ytimg.com/vi/hT_nvWreIhg/hqdefault.jpg",
    color: "#14b8a6",
    secondaryColor: "#8b5cf6",
    featured: false,
    lyrics: [
      "Lately, I've been, I've been losing sleep",
      "Dreaming about the things that we could be",
      "But baby, I've been, I've been praying hard",
      "Said no more counting dollars, we'll be counting stars",
      "Yeah, we'll be counting stars",
      "Take that money, watch it burn",
      "Sink in the river the lessons are learned"
    ]
  },
  {
    id: "track-holly-12",
    title: "Sunflower",
    artist: "Post Malone & Swae Lee",
    album: "Spider-Man: Into the Spider-Verse",
    genre: "Hollywood",
    mood: "Relax",
    duration: 158,
    type: "youtube",
    videoId: "ApXoWvfEYVU",
    audioUrl: "https://www.youtube.com/watch?v=ApXoWvfEYVU",
    embedUrl: "https://www.youtube.com/embed/ApXoWvfEYVU",
    coverUrl: "https://i.ytimg.com/vi/ApXoWvfEYVU/hqdefault.jpg",
    color: "#eab308",
    secondaryColor: "#f97316",
    featured: true,
    lyrics: [
      "Ayy, ayy, ayy, ayy (ooh)",
      "Ooh, ooh, ooh, ooh (aah)",
      "Needless to say, I keep in check",
      "She was a bad-bad, nevertheless (yeah)",
      "Calling it quits now, baby, I'm a wreck (wreck)",
      "Crash at my place, baby, you're a wreck (wreck)",
      "Then you're left in the dust, unless I stuck by ya",
      "You're a sunflower, I think your love would be too much"
    ]
  },
  {
    id: "track-holly-13",
    title: "Circles",
    artist: "Post Malone",
    album: "Hollywood's Bleeding",
    genre: "Hollywood",
    mood: "Relax",
    duration: 215,
    type: "youtube",
    videoId: "wXhTHyIgQ_U",
    audioUrl: "https://www.youtube.com/watch?v=wXhTHyIgQ_U",
    embedUrl: "https://www.youtube.com/embed/wXhTHyIgQ_U",
    coverUrl: "https://i.ytimg.com/vi/wXhTHyIgQ_U/hqdefault.jpg",
    color: "#8b5cf6",
    secondaryColor: "#ec4899",
    featured: false,
    lyrics: [
      "Seasons change and our love went cold",
      "Feed the flame 'cause we can't let go",
      "Run away, but we're running in circles",
      "Run away, run away",
      "I dare you to do something",
      "I'm waiting on you again, so I don't take the blame",
      "Run away, but we're running in circles"
    ]
  },
  {
    id: "track-holly-14",
    title: "That's What I Like",
    artist: "Bruno Mars",
    album: "24K Magic",
    genre: "Hollywood",
    mood: "Energy",
    duration: 206,
    type: "youtube",
    videoId: "PMivT7MJ41M",
    audioUrl: "https://www.youtube.com/watch?v=PMivT7MJ41M",
    embedUrl: "https://www.youtube.com/embed/PMivT7MJ41M",
    coverUrl: "https://i.ytimg.com/vi/PMivT7MJ41M/hqdefault.jpg",
    color: "#f59e0b",
    secondaryColor: "#ef4444",
    featured: false,
    lyrics: [
      "Hey, hey, hey",
      "I got a condo in Manhattan",
      "Baby girl, what's happenin'?",
      "You and your ass invited",
      "So gon' and get to clappin'",
      "Gold jewelry shining so bright",
      "Strawberry champagne on ice",
      "Lucky for you, that's what I like, that's what I like"
    ]
  },
  {
    id: "track-holly-15",
    title: "Wake Me Up",
    artist: "Avicii",
    album: "True",
    genre: "Hollywood",
    mood: "Energy",
    duration: 247,
    type: "youtube",
    videoId: "IcrbM1l_BoI",
    audioUrl: "https://www.youtube.com/watch?v=IcrbM1l_BoI",
    embedUrl: "https://www.youtube.com/embed/IcrbM1l_BoI",
    coverUrl: "https://i.ytimg.com/vi/IcrbM1l_BoI/hqdefault.jpg",
    color: "#10b981",
    secondaryColor: "#f59e0b",
    featured: true,
    lyrics: [
      "Feeling my way through the darkness",
      "Guided by a beating heart",
      "I can't tell where the journey will end",
      "But I know where to start",
      "So wake me up when it's all over",
      "When I'm wiser and I'm older",
      "All this time I was finding myself, and I",
      "Didn't know I was lost"
    ]
  },
  {
    id: "track-holly-16",
    title: "Faded",
    artist: "Alan Walker",
    album: "Different World",
    genre: "Hollywood",
    mood: "Energy",
    duration: 212,
    type: "youtube",
    videoId: "60ItHLz5WEA",
    audioUrl: "https://www.youtube.com/watch?v=60ItHLz5WEA",
    embedUrl: "https://www.youtube.com/embed/60ItHLz5WEA",
    coverUrl: "https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg",
    color: "#06b6d4",
    secondaryColor: "#3b82f6",
    featured: false,
    lyrics: [
      "You were the shadow to my light",
      "Did you feel us?",
      "Another start, you fade away",
      "Afraid our aim is out of sight",
      "Wanna see us alive",
      "Where are you now?",
      "Where are you now?",
      "Under the sea, under the sea",
      "Where are you now? Another dream",
      "You were so lost, I'm faded"
    ]
  },
  {
    id: "track-holly-17",
    title: "See You Again",
    artist: "Wiz Khalifa ft. Charlie Puth",
    album: "Furious 7 Soundtrack",
    genre: "Hollywood",
    mood: "Romantic",
    duration: 237,
    type: "youtube",
    videoId: "RgKAFK5djSk",
    audioUrl: "https://www.youtube.com/watch?v=RgKAFK5djSk",
    embedUrl: "https://www.youtube.com/embed/RgKAFK5djSk",
    coverUrl: "https://i.ytimg.com/vi/RgKAFK5djSk/hqdefault.jpg",
    color: "#3b82f6",
    secondaryColor: "#f59e0b",
    featured: false,
    lyrics: [
      "It's been a long day without you, my friend",
      "And I'll tell you all about it when I see you again",
      "We've come a long way from where we began",
      "Oh, I'll tell you all about it when I see you again",
      "When I see you again",
      "Damn, who knew? All the planes we flew",
      "Good things we've been through",
      "That I'll be standing right here talking to you"
    ]
  },
  {
    id: "track-holly-18",
    title: "Lose Yourself",
    artist: "Eminem",
    album: "8 Mile Soundtrack",
    genre: "Hollywood",
    mood: "Energy",
    duration: 326,
    type: "youtube",
    videoId: "_Yhyp-_hX2s",
    audioUrl: "https://www.youtube.com/watch?v=_Yhyp-_hX2s",
    embedUrl: "https://www.youtube.com/embed/_Yhyp-_hX2s",
    coverUrl: "https://i.ytimg.com/vi/_Yhyp-_hX2s/hqdefault.jpg",
    color: "#64748b",
    secondaryColor: "#0ea5e9",
    featured: false,
    lyrics: [
      "Look, if you had one shot or one opportunity",
      "To seize everything you ever wanted in one moment",
      "Would you capture it or just let it slip?",
      "Yo, his palms are sweaty, knees weak, arms are heavy",
      "There's vomit on his sweater already, mom's spaghetti",
      "He's nervous, but on the surface he looks calm and ready",
      "You better lose yourself in the music, the moment",
      "You own it, you better never let it go"
    ]
  },
  {
    id: "track-holly-19",
    title: "Cornfield Chase & Main Theme",
    artist: "Hans Zimmer",
    album: "Interstellar Soundtrack",
    genre: "Hollywood",
    mood: "Focus",
    duration: 246,
    type: "youtube",
    videoId: "UDVtMYqUAyw",
    audioUrl: "https://www.youtube.com/watch?v=UDVtMYqUAyw",
    embedUrl: "https://www.youtube.com/embed/UDVtMYqUAyw",
    coverUrl: "https://i.ytimg.com/vi/UDVtMYqUAyw/hqdefault.jpg",
    color: "#38bdf8",
    secondaryColor: "#818cf8",
    featured: true,
    lyrics: [
      "Do not go gentle into that good night",
      "Old age should burn and rave at close of day",
      "Rage, rage against the dying of the light",
      "Though wise men at their end know dark is right",
      "Because their words had forked no lightning they",
      "Do not go gentle into that good night",
      "Rage, rage against the dying of the light"
    ]
  },
  {
    id: "track-holly-20",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    genre: "Hollywood",
    mood: "Energy",
    duration: 359,
    type: "youtube",
    videoId: "fJ9rUzIMcZQ",
    audioUrl: "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",
    embedUrl: "https://www.youtube.com/embed/fJ9rUzIMcZQ",
    coverUrl: "https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg",
    color: "#a855f7",
    secondaryColor: "#f59e0b",
    featured: false,
    lyrics: [
      "Is this the real life? Is this just fantasy?",
      "Caught in a landslide, no escape from reality",
      "Open your eyes, look up to the skies and see",
      "I'm just a poor boy, I need no sympathy",
      "Because I'm easy come, easy go, little high, little low",
      "Mama, just killed a man",
      "Put a gun against his head, pulled my trigger, now he's dead"
    ]
  },
  {
    id: "track-holly-21",
    title: "Blank Space",
    artist: "Taylor Swift",
    album: "1989",
    genre: "Hollywood",
    mood: "Energy",
    duration: 231,
    type: "youtube",
    videoId: "e-ORhEE9VVg",
    audioUrl: "https://www.youtube.com/watch?v=e-ORhEE9VVg",
    embedUrl: "https://www.youtube.com/embed/e-ORhEE9VVg",
    coverUrl: "https://i.ytimg.com/vi/e-ORhEE9VVg/hqdefault.jpg",
    color: "#f43f5e",
    secondaryColor: "#ec4899",
    featured: false,
    lyrics: [
      "Nice to meet you, where you been?",
      "I could show you incredible things",
      "Magic, madness, heaven, sin",
      "Saw you there and I thought",
      "'Oh, my God, look at that face'",
      "'Cause, darling, I'm a nightmare dressed like a daydream",
      "Got a long list of ex-lovers, they'll tell you I'm insane",
      "'Cause you know I love the players, and you love the game"
    ]
  },
  {
    id: "track-holly-22",
    title: "Take On Me",
    artist: "a-ha",
    album: "Hunting High and Low",
    genre: "Hollywood",
    mood: "Energy",
    duration: 243,
    type: "youtube",
    videoId: "djV11Xbc914",
    audioUrl: "https://www.youtube.com/watch?v=djV11Xbc914",
    embedUrl: "https://www.youtube.com/embed/djV11Xbc914",
    coverUrl: "https://i.ytimg.com/vi/djV11Xbc914/hqdefault.jpg",
    color: "#06b6d4",
    secondaryColor: "#8b5cf6",
    featured: false,
    lyrics: [
      "We're talking away",
      "I don't know what I'm to say",
      "I'll say it anyway",
      "Today's another day to find you",
      "Shying away",
      "I'll be coming for your love, OK?",
      "Take on me (take on me)",
      "Take me on (take on me)",
      "I'll be gone in a day or two"
    ]
  },

  // ==========================================
  // SPATIAL AMBIENT, SYNTHWAVE & LO-FI
  // ==========================================
  {
    id: "track-spatial-1",
    title: "Quantum Horizon",
    artist: "Aether Void",
    album: "Spatial Dimensions Vol. 1",
    genre: "Synthwave",
    mood: "Energy",
    duration: 182,
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=synthwave-80s-110045.mp3",
    coverUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
    color: "#6366f1",
    secondaryColor: "#ec4899",
    featured: false,
    lyrics: [
      "Gliding through the stellar stream",
      "Neon echoes in a dream",
      "Frequencies that bend the light",
      "Drifting deep into the night",
      "Quantum waves across the sky",
      "Where time and space collide"
    ]
  },
  {
    id: "track-spatial-2",
    title: "Midnight Rain in Shinjuku",
    artist: "Komorebi",
    album: "Tokyo Lo-Fi Memories",
    genre: "Lo-Fi Chill",
    mood: "Relax",
    duration: 145,
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=lofi-study-112191.mp3",
    coverUrl: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=600&q=80",
    color: "#06b6d4",
    secondaryColor: "#3b82f6",
    featured: false,
    lyrics: [
      "Raindrops tapping on the glass",
      "Shadows flicker as they pass",
      "Warm green tea and quiet thoughts",
      "Connecting all the forgotten dots",
      "The city breathes a soft sigh",
      "Underneath the midnight sky"
    ]
  },
  {
    id: "track-spatial-3",
    title: "Neural Resonance",
    artist: "Cyberia 2099",
    album: "Bio-Synthetic Dreams",
    genre: "Cyberpunk",
    mood: "Focus",
    duration: 198,
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f77c30.mp3?filename=cyberpunk-2099-10701.mp3",
    coverUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80",
    color: "#f43f5e",
    secondaryColor: "#8b5cf6",
    featured: false,
    lyrics: [
      "Data pulses through the spine",
      "Synthetic heartbeat out of line",
      "Chromium streets and acid skies",
      "Reflecting in electric eyes",
      "We rewrite the machine code",
      "On this cybernetic road"
    ]
  },
  {
    id: "track-spatial-4",
    title: "Starlight Echoes",
    artist: "Celestia",
    album: "Infinite Voyage",
    genre: "Ambient Space",
    mood: "Sleep",
    duration: 220,
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=deep-ambient-11075.mp3",
    coverUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80",
    color: "#a855f7",
    secondaryColor: "#38bdf8",
    featured: false,
    lyrics: [
      "Dust of nebulae so far",
      "Whispers from a dying star",
      "Floating weightless in the deep",
      "Where cosmic giants softly sleep",
      "Infinite horizon wide",
      "Drifting on the stellar tide"
    ]
  },
  {
    id: "track-spatial-5",
    title: "Sub-Bass Odyssey",
    artist: "Volt Resonance",
    album: "Kinetics",
    genre: "Electronic",
    mood: "Energy",
    duration: 174,
    audioUrl: "https://cdn.pixabay.com/download/audio/2021/08/04/audio_12b0c7443c.mp3?filename=electronic-future-beats-117997.mp3",
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    color: "#a855f7",
    secondaryColor: "#ec4899",
    featured: false,
    lyrics: [
      "Low vibrations shake the floor",
      "Rhythm knocking at the door",
      "Feel the pressure in your chest",
      "Spatial sound at its best",
      "360 degrees of sound",
      "Lifting off the solid ground"
    ]
  },
  {
    id: "track-spatial-6",
    title: "Autumn Breeze & Solitude",
    artist: "Evelyn Ross",
    album: "Acoustic Whispers",
    genre: "Acoustic",
    mood: "Relax",
    duration: 162,
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/02/07/audio_d0a13f69d2.mp3?filename=acoustic-guitars-ambient-11855.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
    color: "#f59e0b",
    secondaryColor: "#ef4444",
    featured: false,
    lyrics: [
      "Golden leaves upon the road",
      "Carrying a gentle load",
      "Six nylon strings softly sing",
      "Memories that seasons bring",
      "Breathe the afternoon away",
      "Into another quiet day"
    ]
  },
  {
    id: "track-spatial-7",
    title: "Celestial Drift",
    artist: "Solaris 7",
    album: "Solar Wind",
    genre: "Synthwave",
    mood: "Focus",
    duration: 190,
    audioUrl: "https://cdn.pixabay.com/download/audio/2023/04/10/audio_fca76c8c45.mp3?filename=synthwave-retro-80s-146399.mp3",
    coverUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80",
    color: "#8b5cf6",
    secondaryColor: "#f43f5e",
    featured: false,
    lyrics: [
      "Arcade lights across the dash",
      "Vector grids that glow and flash",
      "Cruising past the digital sun",
      "The night has only just begun",
      "Accelerate beyond the rim",
      "Where boundaries begin to dim"
    ]
  },
  {
    id: "track-spatial-8",
    title: "Deep Coffee Thoughts",
    artist: "Chillhop Cafe",
    album: "Sunday Brew",
    genre: "Lo-Fi Chill",
    mood: "Relax",
    duration: 156,
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/05/16/audio_db6591201e.mp3?filename=lofi-chill-medium-version-111644.mp3",
    coverUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80",
    color: "#14b8a6",
    secondaryColor: "#f59e0b",
    featured: false,
    lyrics: [
      "Espresso steam in morning light",
      "Everything will be alright",
      "Scratch of vinyl softly spun",
      "Welcoming the morning sun",
      "Peaceful cadence in the air",
      "Nothing urgent, nowhere"
    ]
  }
];

export const GENRES = [
  "All",
  "Bollywood",
  "Hollywood",
  "Romantic",
  "Energy",
  "Relax",
  "Focus",
  "Synthwave",
  "Lo-Fi Chill",
  "Cyberpunk",
  "Ambient Space",
  "Acoustic"
];

export const MOODS = [
  { id: "all", label: "All Vibes", icon: "✨" },
  { id: "Bollywood", label: "Bollywood", icon: "🪕" },
  { id: "Hollywood", label: "Hollywood & Pop", icon: "🎬" },
  { id: "Romantic", label: "Romantic", icon: "💖" },
  { id: "Energy", label: "High Voltage", icon: "⚡" },
  { id: "Relax", label: "Chillout", icon: "☕" },
  { id: "Focus", label: "Deep Focus", icon: "🧠" },
  { id: "Sleep", label: "Dreamscape", icon: "🌙" }
];

export const ENVIRONMENTS = [
  { id: "cosmic", name: "Cosmic Nebula", bgClass: "env-cosmic", desc: "Deep space stellar clouds" },
  { id: "cyber", name: "Cyber Void", bgClass: "env-cyber", desc: "Dark holographic grid" },
  { id: "aurora", name: "Aurora Glow", bgClass: "env-aurora", desc: "Ethereal northern lights" },
  { id: "solarium", name: "Glass Solarium", bgClass: "env-solarium", desc: "Warm dusk luminescence" }
];
